import { Cuisine } from "../models/cuisine.model";
import { Location } from "../models/location.model";
import { Restaurant } from "../models/restaurant.model";

export const RESTAURANTS: Restaurant[] = [
  {
    name: "Tamjai",
    cuisine: Cuisine.CHINESE,
    location: Location.TKO_PLAZA,
    meal: "both",
  },
  {
    name: "First Love",
    cuisine: Cuisine.TAIWANESE,
    location: Location.SEASIDE,
    meal: "both",
  },
  {
    name: "Arome Bake + Drink",
    cuisine: Cuisine.WESTERN,
    location: Location.TKO_PLAZA,
    meal: "lunch",
  },
  {
    name: "Bafan Dumpling",
    cuisine: Cuisine.CHINESE,
    location: Location.TKO_PLAZA,
    meal: "both",
  },
  {
    name: "Uo-Show",
    cuisine: Cuisine.JAPANESE,
    location: Location.TKO_PLAZA,
    meal: "both",
  },
  {
    name: "Mixian Sense",
    cuisine: Cuisine.CHINESE,
    location: Location.POPCORN,
    meal: "both",
  },
  {
    name: "Chicken Factory",
    cuisine: Cuisine.WESTERN,
    location: Location.TKO_PLAZA,
    meal: "both",
  },
  {
    name: "Hung Kee Congee",
    cuisine: Cuisine.CHINESE,
    location: Location.TKO_PLAZA,
    meal: "both",
  },
  {
    name: "MOS Burger Express",
    cuisine: Cuisine.JAPANESE,
    location: Location.TKO_PLAZA,
    meal: "both",
  },
  {
    name: "Mazu",
    cuisine: Cuisine.CHINESE,
    location: Location.TKO_PLAZA,
    meal: "lunch",
  },
  {
    name: "Lane Noodles",
    cuisine: Cuisine.CHINESE,
    location: Location.TKO_PLAZA,
    meal: "both",
  },
  {
    name: "Green Noodle Park Central (CHN)",
    cuisine: Cuisine.CHINESE,
    location: Location.PARK_CENTRAL,
    meal: "both",
  },
  {
    name: "Fairwood",
    cuisine: Cuisine.CHINESE,
    location: Location.POP_WALK,
    meal: "both",
  },
  {
    name: "Cafe de Coral",
    cuisine: Cuisine.CHINESE,
    location: Location.TKO_PLAZA,
    meal: "both",
  },
  {
    name: "Cafe de Coral",
    cuisine: Cuisine.CHINESE,
    location: Location.POPCORN,
    meal: "both",
  },
  {
    name: "Tai Hing",
    cuisine: Cuisine.CHINESE,
    location: Location.TKO_PLAZA,
    meal: "both",
  },
  {
    name: "Tai Cha Fan",
    cuisine: Cuisine.TAIWANESE,
    location: Location.PARK_CENTRAL,
    meal: "lunch",
  },
  {
    name: "Hong Kong Day",
    cuisine: Cuisine.CHINESE,
    location: Location.POPCORN,
    meal: "both",
  },
  {
    name: "Asam Chicken Rice",
    cuisine: Cuisine.SINGAPOREAN,
    location: Location.POPCORN,
    meal: "lunch",
  },
  {
    name: "Sham Tseng Chan Kee Roasted Goose",
    cuisine: Cuisine.CHINESE,
    location: Location.POP_WALK,
    meal: "lunch",
  },
  {
    name: "Bafan Dumpling",
    cuisine: Cuisine.CHINESE,
    location: Location.TKO_PLAZA,
    meal: "both",
  },
  {
    name: "Coco Curry",
    cuisine: Cuisine.JAPANESE,
    location: Location.POP_WALK,
    meal: "both",
  },
  {
    name: "Momoku",
    cuisine: Cuisine.KOREAN,
    location: Location.TKO_PLAZA,
    meal: "both",
  },
  {
    name: "Nijuuichi Don",
    cuisine: Cuisine.JAPANESE,
    location: Location.POP_WALK,
    meal: "both",
  },
  {
    name: "Hachi Sawa",
    cuisine: Cuisine.JAPANESE,
    location: Location.TKO_PLAZA,
    meal: "lunch",
  },
  {
    name: "PHO Locomotive",
    cuisine: Cuisine.VIETNAMESE,
    location: Location.POP_WALK,
    meal: "lunch",
  },
  {
    name: "Daimon Shokudo",
    cuisine: Cuisine.JAPANESE,
    location: Location.TKO_PLAZA,
    meal: "lunch",
  },
  {
    name: "Ah Yung Hotpot",
    cuisine: Cuisine.CHINESE,
    location: Location.TKO_PLAZA,
    meal: "lunch",
  },
  {
    name: "TeaWood",
    cuisine: Cuisine.TAIWANESE,
    location: Location.POPCORN,
    meal: "lunch",
  },
  {
    name: "Butao Ramen",
    cuisine: Cuisine.JAPANESE,
    location: Location.POPCORN,
    meal: "lunch",
  },
  {
    name: "Blumein",
    cuisine: Cuisine.CHINESE,
    location: Location.PARK_CENTRAL,
    meal: "lunch",
  },
  {
    name: "Thai Grill",
    cuisine: Cuisine.THAI,
    location: Location.POP_WALK,
    meal: "lunch",
  },
  {
    name: "Burger Republic",
    cuisine: Cuisine.WESTERN,
    location: Location.POPCORN,
    meal: "both",
  },
  {
    name: "Twelve Flavors",
    cuisine: Cuisine.CHINESE,
    location: Location.PARK_CENTRAL,
    meal: "both",
  },
  {
    name: "Simply Life",
    cuisine: Cuisine.WESTERN,
    location: Location.POPCORN,
    meal: "lunch",
  },
  {
    name: "WHAT THE PHO",
    cuisine: Cuisine.VIETNAMESE,
    location: Location.PARK_CENTRAL,
    meal: "lunch",
  },
  {
    name: "Nha Trang Vietnamese",
    cuisine: Cuisine.VIETNAMESE,
    location: Location.POPCORN,
    meal: "lunch",
  },
  {
    name: "Genki",
    cuisine: Cuisine.JAPANESE,
    location: Location.PARK_CENTRAL,
    meal: "both",
  },
  {
    name: "Taisyou",
    cuisine: Cuisine.JAPANESE,
    location: Location.POPCORN,
    meal: "lunch",
  },
  {
    name: "Tomato 18",
    cuisine: Cuisine.CHINESE,
    location: Location.SEASIDE,
    meal: "both",
  },
  {
    name: "Saizeria",
    cuisine: Cuisine.WESTERN,
    location: Location.TKO_PLAZA,
    meal: "both",
  },
  {
    name: "b + bc cafe",
    cuisine: Cuisine.TAIWANESE,
    location: Location.TKO_PLAZA,
    meal: "lunch",
  },
  {
    name: "Subway",
    cuisine: Cuisine.WESTERN,
    location: Location.POP_WALK,
    meal: "lunch",
  },
  {
    name: "Daily Tea House",
    cuisine: Cuisine.CHINESE,
    location: Location.SEASIDE,
    meal: "lunch",
  },
  {
    name: "Hung Kee Noodles",
    cuisine: Cuisine.CHINESE,
    location: Location.SEASIDE,
    meal: "both",
  },
  {
    name: "MX",
    cuisine: Cuisine.CHINESE,
    location: Location.POP_WALK,
    meal: "both",
  },
  {
    name: "MOMO CLASSIC",
    cuisine: Cuisine.CHINESE,
    location: Location.POP_WALK,
    meal: "both",
  },
  {
    name: "Ben Gor Mixan",
    cuisine: Cuisine.CHINESE,
    location: Location.POP_WALK,
    meal: "both",
  },
  {
    name: "Korean Trojan Food Court",
    cuisine: Cuisine.KOREAN,
    location: Location.POP_WALK,
    meal: "both",
  },
  {
    name: "Grove Cafe",
    cuisine: Cuisine.WESTERN,
    location: Location.SEASIDE,
    meal: "lunch",
  },
  {
    name: "1968 Bistro",
    cuisine: Cuisine.WESTERN,
    location: Location.TKO_SPOT,
    meal: "lunch",
  },
  {
    name: "Super Super Congee and Noodle",
    cuisine: Cuisine.CHINESE,
    location: Location.TKO_SPOT,
    meal: "both",
  },
  {
    name: "Always Happy Burger",
    cuisine: Cuisine.WESTERN,
    location: Location.TKO_SPOT,
    meal: "both",
  },
  {
    name: "Sukiya",
    cuisine: Cuisine.JAPANESE,
    location: Location.TKO_SPOT,
    meal: "both",
  },
  {
    name: "Tsui Wah Restaurant",
    cuisine: Cuisine.CHINESE,
    location: Location.TKO_SPOT,
    meal: "lunch",
  },
  {
    name: "MT Sushi",
    cuisine: Cuisine.JAPANESE,
    location: Location.TKO_SPOT,
    meal: "lunch",
  },
  {
    name: "MI-NE Sushi",
    cuisine: Cuisine.JAPANESE,
    location: Location.TKO_PLAZA,
    meal: "lunch",
  },
  {
    name: "Soup and Rice",
    cuisine: Cuisine.CHINESE,
    location: Location.POP_WALK,
    meal: "lunch",
  },
];
